#!/bin/zsh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/martin/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

xscreensaver -no-splash &
xrdb ~/.Xresources
if [ ! -f /tmp/rdm.lock ]; then
    touch /tmp/rdm.lock
    rdm --daemon -j 20 --log-file ~/.rdm.log
fi

exec fluxbox -log "/home/martin/.fluxbox/log"
