set nocompatible
set background=dark
syntax on
colorscheme desert
set fenc=utf8
set wildmode=list:longest

" set cpoptions=aABceFsmq
"             |||||||||
"             ||||||||+-- When joining lines, leave the cursor
"             |||||||      between joined lines
"             |||||||+-- When a new match is created (showmatch)
"             ||||||      pause for .5
"             ||||||+-- Set buffer options when entering the
"             |||||      buffer
"             |||||+-- :write command updates current file name
"             ||||+-- Automatically add <CR> to the last line
"             |||      when using :@r
"             |||+-- Searching continues at the end of the match
"             ||      at the cursor position
"             ||+-- A backslash has no special meaning in mappings
"             |+-- :write updates alternative file name
"             +-- :read updates alternative file name

filetype plugin indent on
set backspace=indent,eol,start
set clipboard+=unnamed

if has('win32') || has ('win64')
    set directory=$VIM/.vim/tmp
else
    set directory=$HOME/.vim/tmp
endif

set fileformats=unix,mac,dos
set noerrorbells " don't make noise
set virtualedit=onemore
set history=1000
" (XXX: #VIM/tpope warns the line below could break things)
"set iskeyword+=_,$,@,%,#

set incsearch
set laststatus=2
set lazyredraw
set linespace=0
set list
set listchars=tab:>-,trail:-
set showmatch
set matchtime=5
set nostartofline
set novisualbell
set number
set numberwidth=5
set report=0
set ruler
set scrolloff=10
set shortmess=aOstT
set showcmd
set sidescrolloff=10
set statusline=%F%m%r%h%w[%L]%y[%p%%][%04l,%04v]
"              | | | | |  |   |  |     |    |
"              | | | | |  |   |  |     |    + current
"              | | | | |  |   |  |     |       column
"              | | | | |  |   |  |     +-- current line
"              | | | | |  |   |  +-- current % into file
"              | | | | |  |   +-- current syntax in
"              | | | | |  |       square brackets
"              | | | | |  +-- number of lines
"              | | | | +-- preview flag in square brackets
"              | | | +-- help flag in square brackets
"              | | +-- readonly flag in square brackets
"              | +-- modified flag in square brackets
"              +-- full path to file in the buffer

set completeopt=menu
set expandtab
set formatoptions=rq
set ignorecase
set infercase
set nowrap
set shiftround
set smartcase
set shiftwidth=4
set softtabstop=4
set tabstop=8
set textwidth=120
set colorcolumn=0

let b:match_ignorecase = 1
let perl_extended_vars=1

" CtrlP
nmap <Leader>tt :CtrlPTag<Return>                                
nmap <Leader>bb :CtrlPBookmarkDir<Return>                        
let g:ctrlp_extensions = [                                       
            \ 'tag', 'buffertag', 'quickfix',                    
            \ 'line', 'mixed', 'bookmarkdir']                    
let g:ctrlp_match_func = {'match' : 'matcher#cmatch' }           
let g:ctrlp_open_new_file = 't'                                  
let g:ctrlp_root_markers = ['.ctrlp']                            
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
      \ --ignore .git                                            
      \ --ignore .svn                                            
      \ --ignore .hg                                             
      \ --ignore node_modules                                    
      \ --ignore cache                                           
      \ --ignore generated                                       
      \ --ignore _build                                          
      \ --ignore .DS_Store                                       
      \ --ignore "**/*.pyc"                                      
      \ -g ""'


let delimitMate_expand_cr = 1

autocmd Filetype c,cpp setlocal completefunc=RtagsCompleteFunc
autocmd Filetype java setlocal completefunc=javacomplete#Complete

" Haskell
let g:haddock_browser = "open"
let g:haddock_browser_callformat = "%s %s"

" For when you forget to sudo.. Really Write the file.
cmap w!! w !su -c "tee % >/dev/null"

" ColumnColor
hi ColorColumn ctermbg=000

" Use c++11 syntax for c++
au BufNewFile,BufRead *.cpp set syntax=cpp
au BufNewFile,BufRead *.h   set syntax=cpp

" genmake is python
au BufNewFile,BufRead genmake.def       set syntax=python
au BufNewFile,BufRead genmake.def       setfiletype python

" Adding QML syntax highlight
au BufRead,BufNewFile *.qml            setfiletype qml

" Adding asm syntax
au BufRead,BufNewFile *.hla            setfiletype hla
au BufRead,BufNewFile *.asm            setfiletype asmx86

filetype plugin indent on

autocmd FileType javascript,html,xml setlocal shiftwidth=2 softtabstop=2

let g:jsx_ext_required = 0
