if [ -f ~/.profile ]; then
    source ~/.profile
fi

export ZSH=${HOME}/.oh-my-zsh

ZSH_THEME="bira"

CASE_SENSITIVE="true"
export WORKON_HOME=${HOME}/.virtualenvs

plugins=(git virtualenv virtualenvwrapper python)

export PATH="${HOME}/bin:${HOME}/.local/bin:$PATH"
export KBUILD_OUTPUT="${HOME}/kernel_build"
export EDITOR="vim"
export N_PREFIX="$HOME/.local"
export GOPATH="$HOME/.local"

source $ZSH/oh-my-zsh.sh

if [ -f ~/.zshrc.local ]; then
    source ~/.zshrc.local
fi
